schema: "classroom50/repo-config/v1"
classroom: "etc5523"
assignment: "assignment-3"
owner:
  username: "xzha0419"
  id: 264994373
  accepted_at: "2026-10-02T06:10:03Z"
source:
  owner: "ETC5523-2026"
  owner_id: 265932295
  repo: "assignment-3"
  branch: "main"
