---
title: "black-summer"
editor: visual
---

The sky turned orange over southeastern Australia in the summer of 2019-20. The "Black Summer" bush fires burned more than 19 million hectares of land, killed 34 people and destroyed around 5900 homes and other buildings. Smoke has blanketed cities like Sydney and Canberra, nearly 80% Aussies said their living has been affected. Perhaps you are one of them. So, is it only a disaster season or caused by human activity? A major international research has confirmed that comparing to 1900s, the climate change has increased the occurrence of dangerous fire weather at least 30%, and probably much more [@vanoldenborgh2021].

## What happened? And what scientists asked?

In that summer, many people who watching this news asked this question, but its harder to answer than it sounds. A bushfire needs ingredients of hot weather, strong winds, dry vegetation and source of ignition like lightning or human. Climate change will not light fires,and there has not fire season can be blamed on single one factor. Thus scientists asked another question: how much more the climate change increased the probability of hot, dry and windy weather which make the fire spread so far? You can even image that every road could happening car accident, but wet road will strongly increase the probability.
